### ISSUE TITLE
Создать схему базы данных

### ISSUE THREAD

**Issue by levkovalenko** [robot-lab/judyst-backend#2]
- создать схему базы данных
- провести оптимизации в рамках схемы
- задокументировать схему и описание

Зависимости: -

**Comment by danila19991** [comment]
@Rexarrior Можешь написать какие уже сейчас требуются поля в моделях

**Comment by danila19991** [comment]
[ссылка](https://drive.google.com/open?id=1HfWG88q3jd5QXCMTtcQ_LGCancWn91yU) на созданную схему
